"""Homestead gap analysis prompts — one per known topic."""

HOMESTEAD_GAP_PROMPTS = {
    # Soil Health & Amendments
    "soil testing": "Complete guide to soil testing for Zone 7B: what to test for (N-P-K, pH, organic matter, micronutrients), how to take samples, interpreting results, best labs, and how to build an amendment plan from results.",
    "ph level": "Soil pH management for vegetable gardens and fruit trees in Zone 7B: ideal ranges by crop, how to raise pH (lime) vs lower it (sulfur), application rates, how long adjustments take, and testing frequency.",
    "compost": "Composting deep dive: hot vs cold composting, C:N ratios, what to add and avoid, troubleshooting (smell, slow breakdown, pests), bin designs for small homesteads, and how to know when it is finished.",
    "composting": "Composting deep dive: hot vs cold composting, C:N ratios, what to add and avoid, troubleshooting (smell, slow breakdown, pests), bin designs for small homesteads, and how to know when it is finished.",
    "vermicompost": "Vermicomposting complete guide: worm bin setup, red wiggler care, bedding materials, feeding schedule, harvesting castings, troubleshooting (escapees, smell, mites), and using worm castings in the garden.",
    "worm casting": "Worm casting production and use: setting up bins, maintaining populations, harvesting methods, application rates for gardens, making worm casting tea, and storing castings.",
    "mulch": "Mulching strategies for Zone 7B: types (wood chip, straw, leaves, living mulch), depth recommendations by application, when to apply, pros/cons of each, and sourcing free mulch materials.",
    "cover crop": "Cover cropping for small gardens: best species for Zone 7B (crimson clover, winter rye, daikon radish, Austrian peas), when to plant, when to terminate, how to incorporate, and nitrogen fixation benefits.",
    "green manure": "Green manure guide: best species for Zone 7B, planting and incorporation timing, nitrogen contribution estimates, how to terminate without tilling, and fitting green manures into crop rotation.",
    "biochar": "Biochar for garden soil: what it is, how to make it (TLUD method, pit method), charging biochar before use, application rates, long-term soil benefits, and combining with compost.",
    "organic matter": "Building soil organic matter: why it matters, target percentages, methods (compost, mulch, cover crops, biochar), how fast you can build it, and measuring progress over seasons.",
    "amendments": "Organic soil amendments guide: bone meal, blood meal, kelp meal, greensand, rock phosphate, gypsum, azomite — what each does, application rates, when to use, and which ones your Zone 7B garden actually needs.",
    "no-till": "No-till gardening for raised beds and in-ground plots: methods (mulch, cardboard, tarps), transitioning from tilled soil, managing weeds without tilling, planting techniques, and long-term soil health benefits.",
    "hugelkultur": "Hugelkultur beds: design and construction, best wood types (and what to avoid), layering method, first-year nitrogen considerations, watering advantages, and how they perform in hot summers.",
    "mycorrhizae": "Mycorrhizal fungi in the garden: what they do, inoculant products vs building naturally, application methods, which plants benefit most, practices that destroy fungi networks, and no-till connection.",
    "nitrogen fixing": "Nitrogen-fixing plants for the homestead: legume cover crops, perennial nitrogen fixers (autumn olive, black locust, clover), inoculant use, how much nitrogen they actually contribute, and using them in food forest design.",
    # Garden Planning & Layout
    "garden planning": "Annual garden planning process: assessing last season, choosing varieties, calculating planting dates for Zone 7B, mapping beds, succession planting schedule, and seed ordering timeline.",
    "raised bed": "Raised bed design and construction: materials (cedar, galvanized steel, concrete block), sizing, depth requirements, soil mix recipes, drainage, pathways, and cost-effective approaches.",
    "companion planting": "Companion planting guide: proven combinations (three sisters, tomato-basil, carrot-onion), plants that should not be neighbors, trap cropping, and separating companion planting science from myth.",
    "crop rotation": "Crop rotation for small gardens: plant families, rotation groups, minimum rotation years, planning a 4-year rotation, dealing with limited space, and disease prevention benefits.",
    "succession planting": "Succession planting for Zone 7B: which crops to succession plant, timing intervals, calculating last planting dates, spring and fall successions, and maximizing bed use across the full season.",
    "square foot gardening": "Square foot gardening method: grid layout, spacing per crop, soil mix (Mel Mix), vertical growing, intensive planting, and where SFG works well vs where traditional rows are better.",
    "permaculture": "Permaculture principles applied to a small homestead: zones, guilds, stacking functions, water management, perennial systems, food forest design, and practical first steps.",
    "food forest": "Food forest design for Zone 7B: canopy, understory, shrub, herbaceous, groundcover, vine and root layers. Species selection for your climate, guild design, establishment timeline, and maintenance.",
    "zone planning": "Permaculture zone planning for a small homestead: Zone 0-5 layout, placing elements by frequency of use, integrating animals, water, and gardens, and adapting zones to your specific property.",
    "garden map": "Garden mapping: tools and methods (paper, apps, GIS), recording bed layouts, tracking what grew where for rotation, and planning next season from this season map.",
    "bed layout": "Garden bed layout: orientation (N-S vs E-W), sizing for reach, pathway width, maximizing growing space, accounting for shade patterns, and efficient irrigation layout.",
    "row spacing": "Row and plant spacing guide: intensive vs traditional spacing, in-row vs between-row distances for common vegetables, when tight spacing works, and when plants need more room.",
    # Seed Starting & Propagation
    "seed starting": "Seed starting indoors for Zone 7B: timing by crop (count back from last frost), setup (lights, heat mats, trays), soil mix, watering, fertilizing seedlings, and avoiding leggy starts.",
    "germination": "Seed germination guide: temperature requirements by crop, light vs dark germinators, pre-soaking, scarification, stratification, and troubleshooting poor germination rates.",
    "seedling": "Seedling care from emergence to transplant: light requirements, watering technique, when to fertilize, potting up, thinning, and recognizing common seedling problems (damping off, legginess).",
    "transplant": "Transplanting guide: hardening off schedule, best time of day, transplant depth by crop (tomatoes deep, peppers at soil line), reducing transplant shock, and first-week care.",
    "hardening off": "Hardening off seedlings: day-by-day schedule, wind and sun exposure progression, temperature considerations, common mistakes, and shortcuts that actually work.",
    "direct sow": "Direct sowing guide for Zone 7B: which crops to direct sow vs transplant, soil temperature requirements, depth rules, thinning, and protecting direct-sown seeds from birds and pests.",
    "seed saving": "Seed saving basics: open-pollinated vs hybrid, isolation distances, wet vs dry processing, fermentation method for tomatoes, drying, storage conditions, and viability by crop.",
    "propagation": "Plant propagation methods: stem cuttings, root cuttings, division, layering, and grafting. Which method for which plants, rooting hormone use, and success tips.",
    "cuttings": "Propagating from cuttings: softwood vs hardwood cuttings, timing, rooting medium, humidity management, rooting hormone, and best homestead plants to propagate this way (herbs, figs, grapes).",
    "grafting": "Fruit tree grafting: whip-and-tongue, cleft, bark grafts. Rootstock selection, scion collection and storage, timing, aftercare, and when grafting makes sense for the homestead orchard.",
    "cold stratification": "Cold stratification guide: which seeds need it, moist vs dry stratification, duration by species, refrigerator method, winter sowing method, and native plants that require stratification.",
    "seed viability": "Seed viability and storage: shelf life by crop, proper storage conditions (cool, dry, dark), testing germination rates, and when to toss old seed vs plant extra thick.",
    # Season Extension
    "greenhouse": "Greenhouse guide for Zone 7B: types (lean-to, hoop, rigid), sizing, covering materials, ventilation, heating options, what to grow and when, and cost vs benefit for a small homestead.",
    "hoop house": "Hoop house construction and use: sizing, materials (EMT conduit, PVC, cattle panels), covering, ventilation, anchoring, what to grow through winter in Zone 7B, and summer shade use.",
    "cold frame": "Cold frames for Zone 7B: building from recycled materials, sizing, orientation, venting (manual vs automatic), what to grow, hardening off use, and extending the fall harvest.",
    "row cover": "Row cover guide: weight options (light frost vs heavy frost), when to apply, securing methods, using with hoops, pest protection vs frost protection, and reuse and storage.",
    "frost protection": "Frost protection strategies for Zone 7B: monitoring forecasts, row covers, water jugs, mulching, cold frames, choosing frost-tolerant varieties, and emergency measures for unexpected freezes.",
    "season extension": "Season extension toolkit: combining cold frames, row covers, hoop houses, and variety selection to grow food 10-12 months in Zone 7B. Planning fall plantings, overwintering crops, and early spring starts.",
    "winter gardening": "Winter gardening in Zone 7B: crops that grow through winter (spinach, kale, carrots, garlic), planting dates, protection methods, and harvesting through cold months.",
    "microclimate": "Using microclimates on the homestead: identifying warm and cold spots, south-facing walls, thermal mass, windbreaks, cold air drainage, and placing crops to match microclimates.",
    "shade cloth": "Shade cloth for summer gardening: percentage ratings, when to use, mounting methods, which crops benefit in heat in your climate, and combining with irrigation for heat management.",
    "polytunnel": "Polytunnel guide: differences from greenhouse, construction, ventilation challenges, covering replacement, crop planning, and cost analysis for a small homestead.",
    "heat mat": "Seedling heat mats: when they are necessary, thermostat use, which crops need bottom heat, temperature settings, and whether they are worth the investment.",
    "grow light": "Grow lights for seed starting: LED vs fluorescent, light intensity and duration, height management, timer setup, and budget-friendly setups that actually produce stocky transplants.",
    # Vegetable Production
    "tomato": "Tomato production guide for Zone 7B: variety selection (determinate vs indeterminate, heat-tolerant), starting dates, pruning and trellising, common diseases (blight, blossom end rot), and maximizing harvest.",
    "pepper": "Pepper growing in Zone 7B: sweet and hot variety selection, starting early indoors, hardening off, spacing, fertilizing for fruit set, and dealing with warm climates and humidity.",
    "squash": "Squash and zucchini for Zone 7B: summer vs winter types, direct sowing dates, spacing, pollination, squash vine borer prevention, powdery mildew management, and storage of winter squash.",
    "cucumber": "Cucumber production: variety selection (slicing, pickling, burpless), trellising vs ground, succession planting, pollination, bitter fruit causes, and pickle cucumber timing.",
    "beans": "Bean growing guide: bush vs pole, snap vs dry, direct sowing timing for Zone 7B, inoculant use, trellising pole beans, succession planting, and saving seed.",
    "peas": "Pea growing in Zone 7B: snow, snap, and shell peas, fall and spring plantings, trellising, inoculant, harvest timing, and dealing with heat (peas fade fast in warm climate summers).",
    "corn": "Sweet corn for small gardens: variety selection, block planting for pollination, spacing, succession planting, when to harvest (milk stage), and dealing with corn earworm.",
    "potato": "Potato growing: seed potato selection, chitting, planting depth and timing for Zone 7B, hilling methods, container growing, harvest timing, curing, and storage.",
    "garlic": "Garlic growing in Zone 7B: hardneck vs softneck, planting in fall (October-November), mulching, spring care, scape harvest, curing, and storing. Best varieties for the South.",
    "onion": "Onion growing for Zone 7B: short-day vs intermediate-day varieties, starting from seed vs sets vs transplants, planting dates, fertilizing, curing, and storage.",
    "carrot": "Carrot growing: soil preparation (deep, loose, rock-free), variety selection, direct sowing, germination tricks, thinning, succession planting, and fall/winter carrots in Zone 7B.",
    "beet": "Beet growing: variety selection, direct sowing, thinning (each seed is a cluster), spring and fall plantings for Zone 7B, harvesting greens and roots, and storage.",
    "lettuce": "Lettuce production for Zone 7B: varieties that handle heat, spring and fall timing, succession planting every 2 weeks, cut-and-come-again method, bolt prevention, and shade strategies.",
    "kale": "Kale growing: variety selection (lacinato, curly, red Russian), fall planting for sweetness after frost, pest management (cabbage worms), harvest method, and overwintering in Zone 7B.",
    "spinach": "Spinach in Zone 7B: bolt-resistant varieties, fall planting for overwinter harvest, spring window before heat, succession timing, and alternative heat-tolerant greens (Malabar, New Zealand).",
    "broccoli": "Broccoli growing for Zone 7B: transplant timing (spring and fall), variety selection, spacing, side dress fertilizing, harvesting main head and side shoots, and preventing bolting.",
    "cabbage": "Cabbage growing: variety selection, transplant timing for Zone 7B spring and fall crops, spacing, fertilizing, pest management (cabbage looper, imported cabbage worm), and storage.",
    "melon": "Melon growing in Zone 7B: cantaloupe and watermelon varieties, starting indoors vs direct sow, black plastic mulch, pollination, determining ripeness, and trellising small melons.",
    "pumpkin": "Pumpkin growing: variety selection (pie vs decorative vs giant), planting dates for Zone 7B, spacing, vine management, pollination, powdery mildew, and curing for storage.",
    # Herbs & Perennials
    "basil": "Basil growing: variety selection (Genovese, Thai, lemon), starting and transplanting timing for Zone 7B, pinching for bushiness, preventing bolting, preserving (freezing, drying, pesto).",
    "rosemary": "Rosemary in Zone 7B: variety selection, overwintering (borderline hardy), container vs in-ground, drainage requirements, propagation from cuttings, and harvesting.",
    "lavender": "Lavender growing in Zone 7B: variety selection for humidity tolerance, drainage and soil requirements, pruning timing, harvest and drying, and common failure causes in the South.",
    "comfrey": "Comfrey on the homestead: variety selection (Bocking 14 non-spreading), uses (mulch, compost activator, animal feed, fertilizer tea), establishing, harvest frequency, and placement.",
    "asparagus": "Asparagus bed establishment: variety selection, site preparation, crown planting depth and spacing, first-year care, when to start harvesting (year 3), and long-term bed maintenance.",
    "rhubarb": "Rhubarb in Zone 7B: variety selection for warm climates, planting, mulching to keep roots cool, harvest timing and method, dividing crowns, and whether it is realistic in heat in your climate.",
    # Fruit & Orchard
    "fruit tree": "Fruit tree selection and planting for Zone 7B: chill hour requirements, disease-resistant varieties, rootstock sizing, planting technique, first-year care, and realistic production timeline.",
    "apple tree": "Apple growing in Zone 7B: variety selection by chill hours, rootstock choices, pollination partners, pruning (central leader vs open vase), fire blight and cedar-apple rust management.",
    "peach tree": "Peach tree guide for Zone 7B: low-chill and standard varieties, open center pruning, thinning fruit, brown rot and peach leaf curl prevention, and realistic expectations for your region.",
    "pear tree": "Pear growing in Zone 7B: Asian vs European varieties, fire blight resistant selections, rootstock, pruning, harvest timing (pick before ripe), and storage/ripening.",
    "cherry tree": "Cherry growing in Zone 7B: sweet vs sour varieties for warm climates, chill hour concerns, pollination, bird protection, brown rot management, and whether cherries are viable in your region.",
    "plum tree": "Plum growing in Zone 7B: Japanese vs European varieties, low-chill selections, pollination requirements, brown rot and plum curculio management, and thinning fruit.",
    "pruning": "Fruit tree pruning guide: timing (late dormant season), open center vs central leader, heading vs thinning cuts, scaffold branch selection, watersprout removal, and tools. Zone 7B specific timing.",
    "rootstock": "Fruit tree rootstock guide: dwarfing vs semi-dwarf vs standard, rootstock by species (M111, M7 for apple; Lovell, Citation for peach), and how rootstock affects your orchard plan.",
    "berry": "Berry patch establishment: site selection, soil preparation, varieties for Zone 7B, spacing, trellising (where needed), pruning schedules by type, and netting for bird protection.",
    "strawberry": "Strawberry growing in Zone 7B: June-bearing vs everbearing vs day-neutral, planting timing, matted row vs raised bed, runner management, renovation, and winter mulching.",
    "blueberry": "Blueberry growing: soil acidification (sulfur, peat, pine mulch), rabbiteye vs southern highbush for Zone 7B, spacing, pollination, pruning, and realistic yield expectations.",
    "raspberry": "Raspberry growing in Zone 7B: summer-bearing vs everbearing, variety selection for hot summers, trellising, primocane vs floricane pruning, and disease management.",
    "blackberry": "Blackberry growing in Zone 7B: thornless vs thorned varieties, trellising systems, primocane management, pruning after fruit, and dealing with aggressive spreading.",
    "grape": "Grape growing guide: muscadine vs bunch grapes for Zone 7B, trellis systems, pruning (spur vs cane), disease management (black rot, downy mildew), and harvest timing.",
    "pollination": "Fruit tree and garden pollination: self-fertile vs cross-pollination requirements by species, attracting pollinators, hand pollination, and pollination partner spacing.",
    "thinning": "Fruit thinning guide: why thin (bigger fruit, prevent biennial bearing), timing, spacing targets by fruit type, and technique for hand thinning stone fruit and apples.",
    # Pest & Disease Management
    "pest control": "Organic pest control strategy for Zone 7B: IPM approach, identification first, beneficial insects, physical barriers, organic sprays as last resort, and seasonal pest calendar.",
    "integrated pest management": "IPM for the homestead garden: scouting schedule, threshold-based decisions, cultural controls first, biological controls, and when to use organic sprays.",
    "beneficial insect": "Attracting and supporting beneficial insects: which ones matter (ladybugs, lacewings, parasitic wasps, ground beetles), habitat plants, avoiding broad-spectrum sprays, and purchased beneficials.",
    "organic spray": "Organic spray guide: neem oil, Bt, spinosad, copper, sulfur, pyrethrin — what each targets, mixing and application, timing, safety for beneficials, and when each is appropriate.",
    "neem oil": "Neem oil complete guide: what it controls, concentration for different uses, application timing (evening), frequency, mixing properly, storage, and limitations.",
    "bt": "Bacillus thuringiensis (Bt) guide: strains for caterpillars vs beetles vs mosquitoes, application timing, reapplication frequency, safety for beneficials, and organic certification status.",
    "diatomaceous earth": "Diatomaceous earth in the garden: what it controls, food grade vs pool grade, application methods, effectiveness when wet, reapplication, and safety considerations.",
    "blight": "Blight management for tomatoes and potatoes: early blight vs late blight identification, prevention (mulch, spacing, resistant varieties), organic fungicide options, and crop rotation.",
    "mildew": "Powdery and downy mildew: identification, susceptible crops, prevention (spacing, airflow, resistant varieties), organic treatments (milk spray, potassium bicarbonate, neem), and when to remove plants.",
    "aphid": "Aphid management: identification, damage symptoms, beneficial predators (ladybugs, lacewings), water blast, insecticidal soap, neem, and preventing ant-aphid farming.",
    "hornworm": "Tomato hornworm management: identification, hand picking, parasitic wasp encouragement (leave parasitized worms), Bt application, tilling in fall, and companion planting deterrents.",
    "squash bug": "Squash bug management: life cycle, egg identification and removal, trap boards, neem oil timing, resistant varieties, crop rotation, and fall cleanup to break the cycle.",
    "deer fence": "Deer fencing for the garden: fence height requirements, single vs double fence, electric fence options, netting, and cost-effective approaches for small homestead gardens.",
    # Harvest & Preservation
    "harvest": "Harvest timing guide: how to tell when vegetables and fruits are ripe, morning vs evening harvest, handling to preserve quality, and processing timeline after harvest.",
    "canning": "Home canning complete guide: equipment needed, water bath vs pressure canning, when to use each, USDA-tested recipes, safety (botulism prevention), and beginner-friendly recipes.",
    "pressure canning": "Pressure canning guide: equipment (weighted vs dial gauge), testing and maintaining your canner, altitude adjustments, processing times for low-acid foods, and safety protocols.",
    "water bath": "Water bath canning: what can be safely water-bathed (high-acid foods), equipment, processing times, headspace, and troubleshooting (seal failures, floating fruit, siphoning).",
    "pickling": "Pickling guide: quick pickles vs fermented pickles vs canned pickles, vinegar types and ratios, spice blends, cucumber varieties for pickling, and troubleshooting soft pickles.",
    "fermentation": "Lacto-fermentation for food preservation: sauerkraut, kimchi, fermented hot sauce, fermented pickles. Salt ratios, equipment, timing, storage, and troubleshooting (mold, kahm yeast, soft texture).",
    "dehydrating": "Food dehydrating guide: dehydrator selection, temperature settings by food type, pre-treatment (blanching, dipping), dryness testing, conditioning, storage, and best foods to dehydrate.",
    "freeze drying": "Freeze drying for the homestead: machine options and cost, what freeze dries well vs poorly, process basics, mylar bag storage with oxygen absorbers, and cost per batch analysis.",
    "vacuum seal": "Vacuum sealing for food storage: machine types, bag options, freezer storage durations, pantry storage of dry goods, and combining vacuum sealing with other preservation methods.",
    "root cellar": "Root cellar storage: which crops store well (potatoes, carrots, beets, apples, cabbage), ideal conditions (temp, humidity), DIY root cellar options, and monitoring and checking stored produce.",
    "food storage": "Long-term food storage: pantry organization, rotation systems (FIFO), ideal conditions, shelf life of home-preserved foods, and building a year-round homestead pantry from your garden.",
    # Goat Breeds & Selection
    "dairy goat": "Dairy goat overview: comparing breeds by milk volume, butterfat, temperament, and climate tolerance. What to look for when buying, pricing expectations, and starting a small dairy herd.",
    "nigerian dwarf": "Nigerian Dwarf goats: size, milk production (high butterfat), temperament, space requirements, why they are popular for small homesteads, breeding considerations, and realistic expectations.",
    "nubian": "Nubian goats: milk production and butterfat content, temperament (vocal!), heat tolerance for your region, size and space needs, common health issues, and dual-purpose potential.",
    "alpine": "Alpine dairy goats: milk volume, temperament, hardiness, size, and comparison to Nubians for a Zone 7B homestead.",
    "boer": "Boer meat goats: growth rates, feeding for market weight, breeding, kidding ease, parasite resistance, and whether meat goats make sense for a small homestead.",
    # Goat Housing & Fencing
    "goat shelter": "Goat shelter design: size per goat, three-sided vs enclosed, ventilation requirements, bedding options, winter and summer considerations for Zone 7B, and budget-friendly builds.",
    "goat barn": "Goat barn planning: stall sizing, kidding area, milk stand area, feed storage, hay storage, ventilation, predator-proofing, and multi-purpose barn layouts for small homesteads.",
    "goat fencing": "Goat fencing guide: minimum height, fence types that work (and that goats defeat), gate design, electric fence training, and keeping goats IN the fence.",
    "electric fence": "Electric fencing for goats: charger sizing, wire spacing, grounding, training goats to electric, solar vs plug-in chargers, and combining with woven wire.",
    "cattle panel": "Cattle panel fencing and structures: using for goat pens, shelters, garden trellises, and hoop structures. Sourcing, cutting, bending, and connecting panels.",
    "predator protection": "Predator protection for goats and chickens: guardian animals (dogs, llamas, donkeys), secure nighttime housing, fence design, and dealing with coyotes, hawks, and raccoons in your region.",
    "bedding": "Livestock bedding options: straw vs pine shavings vs wood chips, deep litter method, cleaning schedule, composting used bedding, and cost comparison.",
    # Goat Nutrition & Feeding
    "goat feed": "Goat feeding program: hay as primary feed, when to supplement grain, mineral requirements, feeding schedule for does, bucks, and kids, and seasonal adjustments.",
    "hay": "Hay for goats: grass hay vs legume hay (alfalfa), quality indicators, testing hay, storage to prevent mold, feeding methods (rack vs ground), and sourcing in your region.",
    "alfalfa": "Alfalfa for goats: when to feed (lactating does, growing kids), calcium to phosphorus ratio concerns, quantity guidelines, and when grass hay is better.",
    "loose mineral": "Goat minerals: loose mineral vs block (loose is better), what to look for (copper, selenium, zinc), brands, free-choice feeding, and regional deficiencies in your region.",
    "copper bolus": "Copper bolusing goats: why goats need copper, deficiency symptoms, bolus sizing by weight, administration method, frequency, and interaction with other minerals.",
    "body condition score": "Body condition scoring goats: the 1-5 scale, how to feel for condition over the ribs and spine, target scores by life stage, and adjusting feed based on condition.",
    "pasture management": "Pasture management for goats: rotational grazing, rest periods, seeding for goat-friendly forages, browse vs grass, parasite management through rotation, and stocking rates.",
    # Goat Health & Veterinary
    "goat health": "Goat health basics: daily observation checklist, normal vital signs, common diseases in the Southeast, building a goat first aid kit, and when to call a vet vs treat yourself.",
    "hoof trimming": "Goat hoof trimming: frequency, tools, technique, identifying hoof rot and other problems, treating hoof issues, and making trimming easier with proper handling.",
    "deworming": "Goat deworming guide: FAMACHA scoring, fecal egg counts, targeted selective treatment, dewormer classes and rotation, resistance concerns, and alternative parasite management.",
    "famacha": "FAMACHA scoring system: how to check eye membrane color, the 1-5 scale, treatment thresholds, combining with fecal tests, and record keeping for parasite management decisions.",
    "coccidia": "Coccidiosis in goats: prevention in kids, symptoms, treatment (Corid, sulfa drugs), environmental management, and prevention protocols for kidding season.",
    "cdt vaccine": "CDT vaccine for goats: what it prevents (clostridium perfringens C&D, tetanus), schedule for adults and kids, booster timing, and whether other vaccines are needed.",
    "bloat": "Goat bloat: frothy vs free gas bloat, causes, emergency treatment, prevention, recognizing early signs, keeping baking soda available, and when it is a true emergency.",
    "mastitis": "Mastitis in dairy goats: detection (California Mastitis Test), treatment, prevention through proper milking hygiene, dry treatment, and when to cull.",
    "parasite": "Goat parasite management: Haemonchus contortus (barber pole worm), coccidia, liver flukes. Identification, FAMACHA, fecal testing, dewormer resistance, and pasture management.",
    "fecal test": "Fecal egg counting for goats: McMaster method, equipment needed, doing it yourself vs sending to lab, interpreting results, and using counts to guide deworming decisions.",
    # Goat Breeding & Kidding
    "kidding": "Kidding preparation and management: due date calculation, kidding kit contents, signs of labor, normal delivery, when to intervene, immediate kid care, and post-kidding doe care.",
    "breeding": "Goat breeding basics: breeding age and weight, heat cycle timing, buck management, breeding dates for spring kids, hand breeding vs pasture breeding, and record keeping.",
    "heat cycle": "Goat heat cycles: signs of estrus, cycle length, breeding season (fall), out-of-season breeding, buck effect, and using a teaser buck for detection.",
    "kid care": "Newborn kid care: ensuring colostrum intake, navel dipping, monitoring temperature, weak kid protocol, bottle feeding when needed, and first-week milestones.",
    "bottle feeding": "Bottle feeding goat kids: when it is necessary, colostrum sources, milk replacer vs goat milk, feeding schedule by age, weaning timeline, and preventing bottle jaw.",
    "disbudding": "Disbudding goat kids: timing (within first week), methods (disbudding iron), technique, aftercare, and the horns vs no horns decision for the homestead.",
    "weaning": "Weaning goat kids: timing (8-12 weeks depending on purpose), gradual vs abrupt methods, nutrition transition, managing stress, and separating kids from does.",
    # Goat Milking & Dairy
    "milking": "Dairy goat milking: routine establishment, hand milking technique, milk stand training, equipment, sanitation, and dealing with common problems (kicking, holding back milk).",
    "milk stand": "Building a milk stand: dimensions, materials, head catch design, feed trough, training does to the stand, and portable vs permanent options.",
    "milking routine": "Dairy goat milking routine: pre-milking udder care, stripping, milking technique, post-milking teat dip, rapid cooling, and twice-daily schedule management.",
    "udder health": "Goat udder health: anatomy, pre-milking inspection, California Mastitis Test, preventing mastitis, udder edema, teat injuries, and dry-off procedure.",
    "pasteurization": "Goat milk pasteurization: batch vs flash pasteurization, equipment, temperature and time, pros and cons vs raw milk, and legal considerations.",
    "raw milk": "Raw goat milk: safety considerations, proper handling and rapid cooling, testing, shelf life, legal status in your region, and risk reduction protocols.",
    "cheese making": "Goat cheese making at home: chevre (easiest start), cultures and rennet, equipment, process, aging (for hard cheese), and scaling up from kitchen to dedicated space.",
    "goat cheese": "Goat cheese varieties: fresh chevre, feta, aged tomme. Starting with chevre, equipment needed, cultures, rennet types, and troubleshooting common cheese failures.",
    "soap making": "Goat milk soap: cold process method, lye safety, recipe formulation, curing, and whether it is worth doing for the homestead (personal use and potential sales).",
    # Chicken Breeds & Selection
    "layer": "Layer breed selection: production rates, egg color, temperament, heat tolerance for your region, dual-purpose potential, and building a mixed flock for egg variety.",
    "dual purpose": "Dual-purpose chicken breeds for the homestead: breeds that lay well AND have decent carcass size, heritage vs production breeds, and realistic expectations for meat and eggs from one flock.",
    "rhode island red": "Rhode Island Red chickens: production rates, temperament, hardiness, heat tolerance, and why they are a top recommendation for small homesteads.",
    "orpington": "Buff Orpington chickens: egg production, meat quality, broodiness (pro and con), temperament, and heat tolerance concerns for warm summers.",
    "easter egger": "Easter Egger chickens: blue/green egg genetics, production rates, temperament, hardiness, and why they are a fun addition to a homestead flock.",
    # Coop Design & Setup
    "chicken coop": "Chicken coop design: space per bird (4 sq ft inside, 10 sq ft run), ventilation, roost design, nesting boxes, predator-proofing, and materials for Zone 7B climate.",
    "nesting box": "Nesting box design: size, number per hen, height placement, bedding, curtains for privacy, dealing with hens sleeping in boxes, and egg eating prevention.",
    "roost": "Chicken roost design: bar dimensions and shape, spacing between bars, height, poop board below, and why roost design matters for foot health and pecking order.",
    "predator proofing": "Predator-proofing the chicken coop: hardware cloth vs chicken wire, apron or buried fence, automatic door, raccoon-proof latches, and dealing with local predators (raccoons, possums, hawks, snakes).",
    "hardware cloth": "Hardware cloth guide: mesh size for chicken coops (1/2 inch), installation, where to use it (windows, floor, run), and why chicken wire is not enough for predator protection.",
    "deep litter": "Deep litter method for chicken coops: how it works, starting bedding, maintenance (stir, add), when to clean out, composting the result, and benefits vs drawbacks.",
    "automatic door": "Automatic chicken coop doors: options (light sensor vs timer), brands, DIY builds, reliability, and whether the investment is worth it for your flock management.",
    # Chicken Feeding & Nutrition
    "layer feed": "Layer feed guide: protein percentage, calcium content, when to switch from grower, free-choice vs measured feeding, organic vs conventional, and supplementing with forage.",
    "chick starter": "Chick starter feed: medicated vs unmedicated, protein requirements, when to switch to grower, and feeding schedule for the first 8 weeks.",
    "oyster shell": "Oyster shell supplementation: why layers need it, free-choice feeding, when to start, and how it differs from the calcium in layer feed.",
    "grit": "Chicken grit: why free-range chickens may still need it, chick grit vs adult grit, granite vs oyster shell (different purposes), and free-choice feeding.",
    "fermented feed": "Fermented chicken feed: benefits (improved digestion, less waste, probiotics), how to ferment, timeline, containers, and transitioning the flock.",
    "free range": "Free ranging chickens: benefits and risks, supervised vs unsupervised, hawk deterrents, fencing options, impact on egg quality, and managing garden damage.",
    # Egg Production & Management
    "egg production": "Maximizing egg production: breed selection, light management, nutrition, stress reduction, molting support, and realistic expectations by season and hen age.",
    "egg laying": "Egg laying patterns: when pullets start, peak production age, seasonal variation, declining production with age, and managing an aging flock.",
    "egg storage": "Egg storage guide: unwashed on counter vs washed in fridge, bloom preservation, shelf life, water glass preservation method, and freezing eggs.",
    "broody hen": "Managing broody hens: breaking broodiness (when unwanted), using broody hens for hatching, breeds prone to broodiness, and care during brooding.",
    "incubation": "Egg incubation guide: incubator setup, temperature and humidity, turning schedule, candling timeline, lockdown procedure, and troubleshooting failed hatches.",
    "molting": "Chicken molting: why it happens, timing, increased protein needs, reduced egg production, supporting hens through molt, and hard vs soft molts.",
    "winter laying": "Winter egg production: supplemental lighting (14-16 hours total), pros and cons of lighting, cold-hardy breeds, nutrition adjustments, and frozen egg prevention.",
    # Chicken Health
    "chicken health": "Chicken health basics: daily flock observation, normal vs abnormal behavior, common diseases in your region, building a first aid kit, and biosecurity practices.",
    "bumblefoot": "Bumblefoot in chickens: identification, causes, surgical treatment, soaking method, bandaging, prevention (roost design, clean bedding), and when to call a vet.",
    "mites": "Chicken mites and lice: identification, symptoms, treatment (permethrin dust, spray), coop treatment, prevention, and checking for northern fowl mites vs red mites.",
    "coccidiosis": "Coccidiosis in chickens: prevention (medicated starter, Corid), symptoms, treatment, environmental management, and building natural immunity in the flock.",
    "dust bath": "Chicken dust baths: why they are essential, providing a dust bath area, materials (sand, DE, wood ash), covered vs uncovered, and how dust bathing controls parasites.",
    # Chick Raising
    "brooder": "Brooder setup for chicks: container options, heat source, bedding, waterer, feeder, temperature schedule (start 95F, decrease 5F/week), and transitioning to coop.",
    "heat lamp": "Brooder heating: heat lamp safety concerns, heat plate alternatives, temperature monitoring, and gradually reducing heat as chicks feather out.",
    "chick care": "Chick care week by week: temperature needs, feed and water, identifying problems (pasty butt, splayed leg), socialization, and when to move to the coop.",
    "integration": "Integrating new chickens: see-but-not-touch method, age and size matching, supervised introduction, managing pecking order, and timeline for full integration.",
    "pecking order": "Chicken pecking order: normal vs bullying behavior, space requirements to reduce aggression, multiple feed and water stations, and managing flock dynamics.",
    # Rainwater Harvesting
    "rain barrel": "Rain barrel setup: selecting barrels, downspout diverter installation, overflow management, mosquito prevention, winterizing, and connecting multiple barrels.",
    "rainwater harvesting": "Rainwater harvesting system design: calculating roof catchment area, rainfall data for your area AR, storage sizing, first flush diverter, filtration, and legal considerations.",
    "cistern": "Cistern systems: above-ground vs buried, sizing for homestead use, materials (polyethylene, concrete, ferrocement), installation, and connecting to irrigation.",
    "first flush diverter": "First flush diverter: why it matters (roof contaminants), sizing, commercial vs DIY, installation, and maintenance.",
    "roof catchment": "Roof catchment for rainwater: calculating collection area, roofing material safety (metal best, avoid treated wood), gutter sizing, and leaf screening.",
    "rainfall calculation": "Rainwater collection calculations: roof area x rainfall x 0.623 = gallons. your area AR average rainfall (~46 inches/year), monthly distribution, and sizing storage to match garden needs.",
    "ibc tote": "IBC tote for water storage: food-grade sourcing, cleaning, UV protection, connecting multiple totes, overflow, and converting for gravity-fed irrigation.",
    # Water Storage & Distribution
    "water storage": "Water storage options for the homestead: rain barrels, IBC totes, polyethylene tanks, cisterns. Sizing, placement, UV protection, and keeping water clean.",
    "water tank": "Water tank selection: above-ground polyethylene vs buried, sizing for garden irrigation, placement for gravity feed, and UV/algae protection.",
    "gravity fed": "Gravity-fed water systems: elevation requirements (1 PSI per 2.31 feet), tank placement, pipe sizing, flow rate calculations, and designing for drip irrigation.",
    "filtration": "Water filtration for harvested rainwater: sediment filters, carbon filters, UV treatment, when each is needed, maintenance schedules, and garden vs potable use.",
    # Irrigation Systems
    "drip irrigation": "Drip irrigation setup for raised beds and garden rows: components, layout design, emitter spacing by crop, timer programming, winterizing, and troubleshooting.",
    "soaker hose": "Soaker hose irrigation: when to use (vs drip), layout, pressure regulation, mulching over hoses, run time calculations, and lifespan expectations.",
    "irrigation timer": "Irrigation timer guide: battery vs AC powered, zone management, programming for different crop needs, rain delay features, and smart timer options.",
    "irrigation layout": "Irrigation system layout: mainline, sub-mains, laterals, valve placement, zone planning by water needs, and designing for future expansion.",
    "irrigation scheduling": "Irrigation scheduling for Zone 7B: watering depth by crop, frequency by soil type and season, morning watering, adjusting for rainfall, and signs of over/under watering.",
    # Earthworks & Drainage
    "swale": "Swales on the homestead: design on contour, sizing, digging, planting the berm, capturing and infiltrating runoff, and combining with fruit tree plantings.",
    "french drain": "French drain installation: when needed, trench design, gravel and pipe selection, fabric use, outlet placement, and common mistakes.",
    "rain garden": "Rain garden design: sizing, placement (downspout or low area), plant selection for Zone 7B, soil amendment, and managing overflow.",
    "retention pond": "Small retention pond for the homestead: sizing, liner vs clay, overflow design, mosquito management, stocking with mosquitofish, and using for irrigation.",
    "erosion control": "Erosion control on the homestead: identifying problem areas, terracing, ground cover, mulching, swales, and stabilizing slopes with plants.",
    "keyline design": "Keyline design principles: reading the landscape, keypoint and keyline identification, keyline plow use, distributing water across the landscape, and practical application for small properties.",
    # Greywater & Conservation
    "greywater": "Greywater reuse: legal status in your region, safe sources (laundry, shower), what soaps to use, distribution methods (mulch basin), and what to water with greywater.",
    "water conservation": "Water conservation on the homestead: mulching, drip irrigation, timing, drought-tolerant varieties, soil improvement for water retention, and measuring water use.",
    "wicking bed": "Wicking bed construction: reservoir design, overflow, fill pipe, soil layers, geotextile barrier, and which crops thrive in wicking beds.",
    "water audit": "Homestead water audit: measuring current use, identifying waste, calculating garden water needs, matching to rainwater collection potential, and setting conservation goals.",
}

HOMESTEAD_DEFAULT_PROMPT = (
    'Give me a thorough, practical guide on "$TOPIC$" in the context of $CATEGORY$ '
    'for a small homestead in Zone 7B (your location). Include actionable steps, '
    'materials or resources needed, common mistakes, and seasonal timing where relevant.'
)
