"""Health gap analysis prompts — one per known topic."""

HEALTH_GAP_PROMPTS = {
    # Nutrition Mastery
    "protein": "Complete protein guide: optimal daily intake (g/kg), timing around workouts, complete vs incomplete sources, absorption limits per meal, best sources ranked. Evidence-based.",
    "macros": "Macro optimization deep dive: calculating TDEE, setting protein/carb/fat ratios for different goals (muscle gain, fat loss, performance), adjusting over time, tracking methods.",
    "calories": "Caloric management mastery: calculating true maintenance, when to cut/bulk/maintain, rate of change guidelines, metabolic adaptation, diet breaks, reverse dieting.",
    "micronutrients": "Essential micronutrients guide: key vitamins and minerals for performance, common deficiencies in athletes, testing, food sources vs supplements, optimal ranges.",
    "meal timing": "Nutrient timing science: pre/intra/post workout nutrition, protein distribution, carb timing for performance, does meal frequency matter, practical protocols.",
    "hydration": "Elite hydration protocol: daily water needs, electrolyte balance, performance impacts of dehydration, sodium/potassium ratios, hydration tracking.",
    "supplements": "Evidence-based supplement guide: what actually works (creatine, vitamin D, omega-3, etc.), proper dosing, timing, what to skip, quality considerations.",
    "whole foods": "Whole foods optimization: nutrient density ranking, building meals, food quality hierarchy, organic vs conventional, practical meal frameworks.",
    "nutrient timing": "Advanced nutrient timing: anabolic window truth, carb backloading, protein pulsing, fasted training considerations, circadian nutrition.",
    "electrolytes": "Electrolyte mastery: sodium, potassium, magnesium roles, exercise losses, supplementation protocols, signs of imbalance, optimal ratios.",
    # Strength Foundation
    "progressive overload": "Progressive overload systems: methods beyond adding weight, double progression, rep PRs, volume landmarks, when to reset, periodization integration.",
    "compound movements": "Compound lift mastery: the big 4+ movements, proper sequencing, frequency optimization, technique priorities, accessory pairing.",
    "squat": "Squat optimization: high bar vs low bar, stance width, depth standards, mobility requirements, common faults, programming considerations.",
    "deadlift": "Deadlift deep dive: conventional vs sumo, setup checklist, hip hinge mastery, grip options, frequency and recovery, accessory work.",
    "bench press": "Bench press technique: arch and leg drive, grip width, bar path, shoulder health, variations, plateau-breaking strategies.",
    "hypertrophy": "Hypertrophy training science: optimal rep ranges, volume landmarks (MEV/MAV/MRV), frequency per muscle, exercise selection, mind-muscle connection.",
    "periodization": "Periodization models: linear vs undulating vs block, how to structure mesocycles, deload timing, peaking, long-term planning.",
    "volume": "Training volume optimization: sets per muscle per week, volume landmarks, individual variation, volume accumulation, recovery capacity.",
    "intensity": "Intensity management: RPE vs percentage-based, RIR tracking, when to push vs back off, intensity techniques (drop sets, rest-pause).",
    "deload": "Strategic deloading: when to deload (proactive vs reactive), deload structures (volume vs intensity reduction), maintaining gains, return protocols.",
    # Recovery & Sleep
    "sleep": "Sleep optimization protocol: sleep stages importance, optimizing deep sleep and REM, sleep architecture, tracking, environment setup, timing.",
    "deep sleep": "Maximizing deep sleep: factors that increase SWS, temperature manipulation, timing, supplements that help, training considerations.",
    "recovery": "Recovery systems: active vs passive, monitoring readiness (HRV, subjective), recovery modalities ranked by evidence, programming recovery.",
    "cold exposure": "Cold exposure protocols: cold showers vs ice baths, temperature and duration, timing relative to training, adaptation, benefits and risks.",
    "sauna": "Sauna protocol guide: temperature and duration, frequency, cardiovascular benefits, growth hormone claims, heat acclimation, safety.",
    "mobility": "Mobility training: assessment, priority areas for lifters, programming mobility work, dynamic vs static, when mobility limits gains.",
    "stretching": "Stretching science: static vs dynamic vs PNF, when each is appropriate, duration, frequency, stretching for performance vs flexibility.",
    "foam rolling": "Foam rolling and SMR: what it actually does, technique, timing (pre vs post), duration, tools compared, realistic expectations.",
    "active recovery": "Active recovery strategies: low intensity movement, blood flow benefits, what activities work, frequency, avoiding interference.",
    "sleep hygiene": "Sleep hygiene checklist: light exposure timing, temperature, caffeine cutoff, screen management, wind-down routine, consistency.",
    # Cardiovascular Health
    "zone 2": "Zone 2 training mastery: determining your zones, duration and frequency, benefits for health and performance, methods (MAF, lactate testing), combining with lifting.",
    "vo2 max": "VO2 max optimization: testing methods, training to improve it, why it matters for longevity, realistic improvement rates, protocol design.",
    "cardio": "Cardio for lifters: types ranked, minimum effective dose, interference effect management, timing relative to lifting, cardio that builds vs burns.",
    "hiit": "HIIT protocols: true HIIT vs marketing HIIT, work:rest ratios, frequency limits, recovery demands, when HIIT beats steady state.",
    "liss": "LISS cardio guide: heart rate targets, duration, frequency, best modalities, benefits for recovery, fitting with strength training.",
    "endurance": "Building endurance base: aerobic system development, volume progression, polarized training, endurance for non-endurance athletes.",
    "lactate threshold": "Lactate threshold training: testing, threshold workouts, tempo runs, progression, relationship to performance.",
    "conditioning": "Conditioning for strength athletes: energy system work, GPP, work capacity building, conditioning that supports lifting.",
    "heart rate": "Heart rate training: zones explained, monitoring methods, resting HR trends, HR variability basics, practical application.",
    "cycling": "Cycling for lifters: low impact cardio benefits, bike setup, workout structures, indoor vs outdoor, power-based training basics.",
    # Hormone Optimization
    "testosterone": "Natural testosterone optimization: sleep, nutrition, training, stress, body composition, realistic expectations, when to test, reference ranges.",
    "cortisol": "Cortisol management: acute vs chronic elevation, training impact, lifestyle factors, measurement timing, optimization strategies.",
    "insulin": "Insulin sensitivity: why it matters, improving sensitivity, carb timing, fasted states, metabolic flexibility, testing.",
    "thyroid": "Thyroid function: T3/T4/TSH basics, metabolism connection, common issues in dieters, testing, lifestyle factors.",
    "growth hormone": "Growth hormone naturally: sleep optimization, fasting effects, training stimulus, realistic expectations vs hype.",
    "bloodwork": "Essential bloodwork panel: what to test, optimal vs normal ranges, frequency, interpreting results, working with doctors.",
    "biomarkers": "Key biomarkers for performance: inflammation markers, lipids, glucose, hormones, vitamins, tracking over time.",
    "metabolic health": "Metabolic health markers: fasting glucose, insulin, triglycerides, waist circumference, metabolic syndrome prevention.",
    "labs": "Lab testing guide: what panels to order, timing, fasted requirements, tracking changes, red flags to watch.",
    "hormone optimization": "Holistic hormone optimization: lifestyle factors pyramid, sleep/stress/nutrition/training integration, realistic natural limits.",
    # Longevity Science
    "longevity": "Longevity fundamentals: healthspan vs lifespan, key drivers, lifestyle interventions ranked by evidence, testing, practical protocols.",
    "autophagy": "Autophagy deep dive: what it is, triggers (fasting, exercise), duration needed, practical application, overhyped claims vs reality.",
    "mitochondria": "Mitochondrial health: why it matters, exercise types that help, cold exposure, fasting, supplements with evidence, testing.",
    "healthspan": "Maximizing healthspan: the pillars (exercise, nutrition, sleep, stress), prevention focus, screening recommendations, lifestyle medicine.",
    "aging": "Aging biology basics: hallmarks of aging, what we can influence, interventions with evidence, tracking biological age.",
    "nad+": "NAD+ and longevity: the science, precursors (NMN, NR), dosing, realistic expectations, alternatives, current evidence state.",
    "sirtuins": "Sirtuins explained: what they do, activation methods, fasting connection, resveratrol debate, practical takeaways.",
    "telomeres": "Telomere biology: what they indicate, lifestyle factors that affect length, testing value, realistic intervention expectations.",
    "fasting": "Fasting protocols compared: 16:8, OMAD, 24-48hr fasts, extended fasting, benefits by duration, who should/shouldnt fast.",
    "caloric restriction": "Caloric restriction for longevity: the research, practical implementation, CR mimetics, muscle preservation, who benefits.",
    # Mental Performance
    "focus": "Focus optimization: attention training, environment design, deep work protocols, distraction management, pharmaceutical-free enhancement.",
    "cognition": "Cognitive performance: nutrition for brain, exercise effects, sleep impact, nootropics with evidence, brain training reality.",
    "meditation": "Meditation for performance: styles compared, minimum effective dose, building habit, measurable benefits, practical protocols.",
    "breathwork": "Breathwork protocols: box breathing, Wim Hof, physiological sigh, when to use each, stress response control.",
    "stress management": "Stress management systems: acute vs chronic stress, HRV monitoring, lifestyle interventions, when stress helps performance.",
    "neuroplasticity": "Neuroplasticity basics: how learning works, factors that enhance it, exercise connection, practical application.",
    "brain health": "Long-term brain health: risk factors, protective factors, exercise importance, nutrition, sleep, cognitive reserve.",
    "mental clarity": "Mental clarity optimization: blood sugar stability, hydration, sleep quality, exercise timing, elimination factors.",
    "nootropics": "Nootropics evidence review: what works (caffeine, creatine), what doesnt, stacking considerations, safety, realistic expectations.",
    "flow state": "Accessing flow states: triggers, conditions, training for flow, measurement, application to training and work.",
    # Body Composition
    "body fat": "Body fat measurement: methods compared (DEXA, calipers, etc.), accuracy, tracking trends, healthy ranges by age/sex.",
    "lean mass": "Maximizing lean mass: training priorities, nutrition requirements, realistic gain rates, plateau breaking, long-term strategy.",
    "muscle mass": "Muscle building fundamentals: stimulus, nutrition, recovery triangle, programming for hypertrophy, tracking progress.",
    "recomp": "Body recomposition: who its for, how it works, nutrition setup, training approach, realistic timeline, tracking.",
    "cutting": "Cutting protocol: rate of loss, protein needs, training adjustments, diet breaks, ending the cut, maintaining muscle.",
    "bulking": "Smart bulking guide: lean bulk setup, calorie targets, monitoring fat gain, when to stop, transition to cutting.",
    "maintenance": "Finding true maintenance: reverse dieting, diet breaks, metabolic adaptation, long-term maintenance strategies.",
    "metabolic rate": "Metabolic rate factors: TDEE components, adaptation, boosting metabolism myths vs reality, measurement methods.",
    "dexa": "DEXA scanning guide: what it measures, accuracy, frequency, tracking changes, interpreting results, limitations.",
    "body composition": "Body composition mastery: beyond the scale, measurement methods, setting goals, realistic timelines, tracking systems.",
    # Biohacking & Tracking
    "hrv": "HRV for performance: what it measures, devices, interpreting data, using HRV to guide training, limitations.",
    "cgm": "Continuous glucose monitoring: what you learn, patterns to watch, food responses, optimal ranges, who benefits.",
    "wearables": "Wearables compared: Whoop vs Oura vs Apple Watch vs Garmin, what metrics matter, actionable data, limitations.",
    "tracking": "Performance tracking systems: what to track, tools, avoiding paralysis, minimum effective tracking, long-term trends.",
    "quantified self": "Quantified self framework: n=1 experiments, tracking systems, data interpretation, actionable insights, avoiding obsession.",
    "biohacking": "Evidence-based biohacking: interventions ranked, cost-benefit analysis, diminishing returns, fundamentals before hacks.",
    "optimization": "Performance optimization hierarchy: fundamentals first, marginal gains, personalization, avoiding overthinking.",
    "protocol": "Building protocols: morning routines, pre-workout, recovery, sleep - systematic approach to consistency.",
    "routine": "Routine design: habit stacking, minimum viable routines, flexibility, travel adjustments, long-term sustainability.",
    "consistency": "Consistency systems: habit formation, environment design, tracking, accountability, recovering from breaks.",
    # Advanced Protocols
    "intermittent fasting": "IF protocols deep dive: 16:8, 18:6, OMAD, alternate day - who benefits, muscle preservation, training timing, breaking fasts.",
    "keto": "Ketogenic diet for athletes: adaptation period, performance considerations, targeted keto, cyclical keto, electrolytes.",
    "carnivore": "Carnivore diet examination: potential benefits, risks, nutrient considerations, who might benefit, implementation.",
    "contrast therapy": "Contrast therapy protocols: hot/cold cycling, timing, duration, recovery benefits, practical implementation.",
    "ice bath": "Ice bath protocols: temperature, duration, timing relative to training, adaptation considerations, building tolerance.",
    "time under tension": "Time under tension training: tempo manipulation, hypertrophy applications, strength considerations, programming.",
    "mind muscle connection": "Mind-muscle connection: the science, developing it, when it matters, internal vs external focus.",
    "tempo": "Tempo training: notation explained, applications, eccentric emphasis, pauses, programming tempo work.",
    "creatine": "Creatine complete guide: dosing, timing, loading debate, water retention, safety, forms compared, who responds.",
}

HEALTH_DEFAULT_PROMPT = 'Give me an elite-level deep dive on "$TOPIC$" in the context of $CATEGORY$. Evidence-based, practical protocols, what actually works. Include implementation details and realistic expectations.'
